import { Uniqueid } from "../uniqueId.mjs";

const uuidRegex =
  /^[0-9A-F]{8}-[0-9A-F]{4}-[4][0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i;

describe("uniqueId", () => {
  it("should be generated uuid", () => {
    const data = Uniqueid.create();
    expect(data.getValue()).toMatch(uuidRegex);
  });
  it("should be generated by specific id", () => {
    const stub = Uniqueid.create("some_id");
    expect(stub.isEqualString("some_id"));
    expect(stub.isEqual(stub));
  });
});
